export function getRandomInt(max) {
  return Math.floor(Math.random() * Math.floor(max))
}

export function randomElement(array) {
  return array[getRandomInt(array.length)]
}

const physique = [
  'Athletic',
  'Brawny',
  'Corpulent',
  'Delicate',
  'Gaunt',
  'Hulking',
  'Lanky',
  'Ripped',
  'Rugged',
  'Scrawny',
  'Short',
  'Sinewy',
  'Slender',
  'Flabby',
  'Statuesque',
  'Stout',
  'Tiny',
  'Towering',
  'Willowy',
  'Wiry',
]

const face = [
  'Bloated',
  'Blunt',
  'Bony',
  'Chiseled',
  'Delicate',
  'Elongated',
  'Patrician',
  'Pinched',
  'Hawkish',
  'Broken',
  'Impish',
  'Narrow',
  'Ratlike',
  'Round',
  'Sunken',
  'Sharp',
  'Soft',
  'Square',
  'Wide',
  'Wolfish',
]

const skin = [
  'Battle Scar',
  'Birthmark',
  'Burn Scar',
  'Dark',
  'Makeup',
  'Oily',
  'Pale',
  'Perfect',
  'Pierced',
  'Pockmarked',
  'Reeking',
  'Tattooed',
  'Rosy',
  'Rough',
  'Sallow',
  'Sunburned',
  'Tanned',
  'War Paint',
  'Weathered',
  'Whip Scar',
]

const hair = [
  'Bald',
  'Braided',
  'Bristly',
  'Cropped',
  'Curly',
  'Disheveled',
  'Dreadlocks',
  'Filthy',
  'Frizzy',
  'Greased',
  'Limp',
  'Long',
  'Luxurious',
  'Mohawk',
  'Oily',
  'Ponytail',
  'Silky',
  'Topknot',
  'Wavy',
  'Wispy',
]

const clothing = [
  'Antique',
  'Bloody',
  'Ceremonial',
  'Decorated',
  'Eccentric',
  'Elegant',
  'Fashionable',
  'Filthy',
  'Flamboyant',
  'Stained',
  'Foreign',
  'Frayed',
  'Frumpy',
  'Livery',
  'Oversized',
  'Patched',
  'Perfumed',
  'Rancid',
  'Torn',
  'Undersized',
]

const virtue = [
  'Ambitious',
  'Cautious',
  'Courageous',
  'Courteous',
  'Curious',
  'Disciplined',
  'Focused',
  'Generous',
  'Gregarious',
  'Honest',
  'Honorable',
  'Humble',
  'Idealistic',
  'Just',
  'Loyal',
  'Merciful',
  'Righteous',
  'Serene',
  'Stoic',
  'Tolerant',
]

const vice = [
  'Aggressive',
  'Arrogant',
  'Bitter',
  'Cowardly',
  'Cruel',
  'Deceitful',
  'Flippant',
  'Gluttonous',
  'Greedy',
  'Irascible',
  'Lazy',
  'Nervous',
  'Prejudiced',
  'Reckless',
  'Rude',
  'Suspicious',
  'Vain',
  'Vengeful',
  'Wasteful',
  'Whiny',
]

const speech = [
  'Blunt',
  'Booming',
  'Breathy',
  'Cryptic',
  'Drawling',
  'Droning',
  'Flowery',
  'Formal',
  'Gravelly',
  'Hoarse',
  'Mumbling',
  'Precise',
  'Quaint',
  'Rambling',
  'Rapid-fire',
  'Dialect',
  'Slow',
  'Squeaky',
  'Stuttering',
  'Whispery',
]
const background = [
  'Alchemist',
  'Beggar',
  'Butcher',
  'Burglar',
  'Charlatan',
  'Cleric',
  'Cook',
  'Cultist',
  'Gambler',
  'Herbalist',
  'Magician',
  'Mariner',
  'Mercenary',
  'Merchant',
  'Outlaw',
  'Performer',
  'Pickpocket',
  'Smuggler',
  'Student',
  'Tracker',
]

const misfortunes = [
  'Abandoned',
  'Addicted',
  'Blackmailed',
  'Condemned',
  'Cursed',
  'Defrauded',
  'Demoted',
  'Discredited',
  'Disowned',
  'Exiled',
  'Framed',
  'Haunted',
  'Kidnapped',
  'Mutilated',
  'Poor',
  'Pursued',
  'Rejected',
  'Replaced',
  'Robbed',
  'Suspected',
]

const armor = [
  'Gambeson',
  'Brigandine',
  'Chain',
]

const helmetsAndShields = [
  'Helmet',
  'Shield',
  'Helmet and Shield',
]

const dungeoneeringGear = [
  'Rope, 50ft',
  'Pulleys',
  'Candles, 5',
  'Chain, 10ft',
  'Chalk, 10',
  'Crowbar',
  'Tinderbox',
  'Grappling hook',
  'Hammer',
  'Waterskin',
  'Lantern',
  'Lamp oil',
  'Padlock',
  'Manacles',
  'Mirror',
  'Pole, 10ft',
  'Sack',
  'Tent',
  'Spikes, 5',
  'Torches, 5',
]

const generalGear1 = [
  'Air bladder',
  'Bear trap',
  'Shovel',
  'Bellows',
  'Grease',
  'Saw',
  'Bucket',
  'Caltrops',
  'Chisel',
  'Drill',
  'Fishing rod',
  'Marbles',
  'Glue',
  'Pick',
  'Hourglass',
  'Net',
  'Tongs',
  'Lockpicks',
  'Metal file',
  'Nails',
]

const generalGear2 = [
  'Incense',
  'Sponge',
  'Lens',
  'Perfume',
  'Horn',
  'Bottle',
  'Soap',
  'Spyglass',
  'Tar pot',
  'Twine',
  'Fake jewels',
  'Blank book',
  'Card deck',
  'Dice set',
  'Cook pots',
  'Face paint',
  'Whistle',
  'Instrument',
  'Quill & Ink',
  'Small bell',
]
const backgroundDescription = [
  'Urchin. You grew up in the merciless streets of a large city',
  'Wanted. There\'s a price on your head, but you have allies',
  'Cult Initiate. You know blasphemous secrets and rituals',
  'Thieves\' Guild. You have connections, contacts, and debts',
  'Banished. Your people cast you out for supposed crimes',
  'Orphaned. An unusual guardian rescued and raised you',
  'Wizard\'s Apprentice. You have a knack and eye for magic',
  'Jeweler. You can easily appraise value and authenticity',
  'Herbalist. You know plants, medicines, and poisons',
  'Barbarian. You left the horde, but it never quite left you',
  'Mercenary. You fought friend and foe alike for your coin',
  'Sailor. Pirate, privateer, or merchant — the seas are yours',
  'Acolyte. You\'re well trained in religious rites and doctrines',
  'Soldier. You served as a fighter in an organized army',
  'Ranger. The woods and wilds are your true home',
  'Scout. You survived on stealth, observation, and speed',
  'Minstrel. You\'ve traveled far with your charm and talent',
  'Scholar. You know much about ancient history and lore',
  'Noble. A famous name has opened many doors for you',
  'Chirurgeon. You know anatomy, surgery, and first aid',
]
const careers = [
  'Acolyte: candlestick, censer, incense',
  'Acrobat: flash powder, balls, lamp oil',
  'Actor: wig, makeup, costume',
  'Alchemist: acid, mortar/pestle, 6 vials',
  'Antiquarian: old coin, flag, lore book',
  'Arcanist: spell book, arcane robes, chalk',
  'Architect: plumb line, level, ruler',
  'Assassin: crossbow, garrote, soft boots',
  'Astrologer: star charts, almanac, telescope',
  'Baker: rolling pin, flour bag, lard block',
  'Bandit: mask, manacles, caltrops',
  'Barber: scissors, hair oil, straight razor',
  'Beast Tamer: whip, gloves, leash',
  'Beekeeper: honey, mask, smoke bomb',
  'Blacksmith: hammer, bellows, tongs',
  'Boatman: 10’ pole, instrument, paddle',
  'Bookbinder: sewing kit, glue, quill/ink',
  'Brewer: mash paddle, beer keg, hops',
  'Burglar: lockpicks, grappling hook, rope',
  'Butcher: cleaver, meat hook, bacon',
  'Candlemaker: 10 candles, lamp oil, wax',
  'Carpenter: hammer, saw, box of nails',
  'Charlatan: costume, fake elixir, degree',
  'Cobbler: leather roll, fancy shoes, tacks',
  'Coachman: whip, lockbox, oilskin coat',
  'Cook: frying pan, salt, olive oil',
  'Courier: oilskin bag, local map, lantern',
  'Courtier: perfume, wig, fan',
  'Cultist: dagger, ritual robes, amulet',
  'Cutpurse: knife, caltrops, sack',
  'Dyer: 10’ pole, dyes, soap',
  'Explorer: sextant, spyglass, crampons',
  'Falconer: bird cage, gloves, whistle',
  'Fence: short sword, file, sealing wax',
  'Fisherman: spear, net, fishing tackle',
  'Folklorist: prophecy, bones, scales',
  'Gambler: rapier, card deck, dice',
  'Gamekeeper: sling, horn, rope ladder',
  'Gardener: sickle, shovel, shears',
  'Grave Robber: saw, crowbar, pulleys',
  'Gravedigger: shovel, pickaxe, bucket',
  'Groom: oats, horse brush, blanket',
  'Guard: halberd, livery, horn',
  'Headsman: axe, hood, garrote',
  'Herbalist: herbs, sickle, herb manual',
  'Hunter: tent, bearskin, bear trap',
  'Innkeeper: ladle, 10 candles, cauldron',
  'Inquisitor: manual, vestments, pliers',
  'Investigator: journal, manacles, vial',
  'Jailer: padlock, 10’ chain, wine jug',
  'Jester: scepter, donkey head, motley',
  'Jeweler: pliers, loupe, tweezers',
  'Knight: lady’s favor, banner, signet ring',
  'Kidnapper: chloroform, manacles, hood',
  'Lawyer: fancy robe, law book, certificate',
  'Locksmith: crowbar, picks, padlock',
  'Mason: chisel, hammer, chalk',
  'Merchant: scales, strongbox, bag of spice',
  'Miner: pickaxe, lantern, pet canary',
  'Musician: 3 instruments',
  'Naturalist: fossil, insect case, geode',
  'Officer: shoe polish, medal, spyglass',
  'Oracle: tea leaves, tarot deck, crystal',
  'Orator: 100 marbles, bullhorn, wax tablet',
  'Painter: linseed oil, pigments, brushes',
  'Peddler: bucket, 300’ twine, mirror',
  'Philosopher: staff, lantern, chalk',
  'Physician: saw, scalpel, wine jug',
  'Pilgrim: staff, relic, letter of passage',
  'Pirate: sextant, cannonball, grappling hook',
  'Pit Fighter: net, whip, wine jug',
  'Playwright: quill/ink, skull, 10 candles',
  'Poacher: animal scent, bow, 20 arrows',
  'Poet: stationery, bell, perfume',
  'Priest: holy water, 10 stakes, prayer book',
  'Prospector: 10 iron spikes, pickaxe, pan',
  'Puppeteer: confetti, puppet, sewing kit',
  'Rat Catcher: cage, 10 rat traps, sack',
  'Saboteur: air bladder, crowbar, bomb',
  'Sailor: beeswax, pullies, spyglass',
  'Scout: signal flags, black grease, dice',
  'Scribe: lamp oil, quill/ink, sealing wax',
  'Sculptor: chisel, clay, calipers',
  'Servant: sponge, silverware, poker',
  'Shepherd: crook, instrument, sling',
  'Shipwright: drill, hammer, axe',
  'Singer: mirror, makeup, locket',
  'Smuggler: pulleys, rope, makeup',
  'Soldier: tent, card deck, shovel',
  'Spy: caltrops, poison, forged papers',
  'Squire: torch, armor polish, trumpet',
  'Tailor: sewing kit, scissors, soap',
  'Tattooist: soot pot, needles, 10 candles',
  'Thieftaker: bear trap, manacles, torch',
  'Thug: poison, knife, lamp oil',
  'Torturer: drill, hourglass, 10’ chain',
  'Trapper: bear trap, 300’ twine, bear pelt',
  'Watchman: lantern, trumpet, spear',
  'Woodcutter: axe, firewood, 50’ rope',
]

const travelShifts = [
  'Acid rain',
  'Animal migration',
  'Anvil cloud',
  'Ash cloud',
  'Ash rain',
  'Aurora',
  'Avalanche',
  'Ball lightning',
  'Bird migration',
  'Black blizzard',
  'Blizzard',
  'Blood moon',
  'Brush fire',
  'City event',
  'Cloudburst',
  'Cold wave',
  'Cold weather',
  'Color sky',
  'Delusion',
  'Dense fog',
  'Disaster',
  'Downburst',
  'Drizzle',
  'Dust devil',
  'Dust storm',
  'Earthquake',
  'Effect rain',
  'Electric storms',
  'Element rain',
  'Fire whirls',
  'Fireflies',
  'Firestorms',
  'Flash flood',
  'Flooding',
  'Fluffy clouds',
  'Fog',
  'Food rain',
  'Forest fire',
  'Freezing fog',
  'Freezing rain',
  'Grass fire',
  'Haboob',
  'Hail',
  'Hailstorm',
  'Haze',
  'Heat lightning',
  'Heatwave',
  'Heavy rain',
  'Hot weather',
  'Hot winds',
  'Humidity',
  'Hurricane',
  'Ice storm',
  'Insect swarm',
  'Landslide',
  'Lava flow',
  'Light winds',
  'Lunar eclipse',
  'Meteor shower',
  'Mirage',
  'Mist',
  'Misty rain',
  'Monsoon',
  'Mudflow',
  'Murmuration',
  'Northern lights',
  'Overcast',
  'Planet alignment',
  'Pollen cloud',
  'Pyroclastic flow',
  'Rain of fish',
  'Rain of frogs',
  'Rain of worms',
  'Rainbow',
  'Salt storm',
  'Sandstorm',
  'Scent',
  'Showers',
  'Smog',
  'Smoke',
  'Solar eclipse',
  'Sound',
  'Stampede',
  'Star jelly',
  'Steam devils',
  'Strong winds',
  'Sulfur clouds',
  'Swamp lights',
  'Taste rain',
  'Texture rain',
  'Thunderstorms',
  'Tornado',
  'Tremors',
  'Volcanic bombs',
  'Warm rain',
  'Warm winds',
  'Waterspouts',
  'Weapon rain',
  'Windstorm',
  'Wispy clouds',
]

const qualities = [
  'Abnormal',
  'Abominable',
  'Advanced',
  'Ancestral',
  'Ancient',
  'Arcane',
  'Artful',
  'Baleful',
  'Bizarre',
  'Canonical',
  'Celestial',
  'Cerebral',
  'Chaotic',
  'Color',
  'Cosmic',
  'Crafty',
  'Cryptic',
  'Curious',
  'Detestable',
  'Dismal',
  'Dreadful',
  'Elder',
  'Eldritch',
  'Enigmatic',
  'Esoteric',
  'Excellent',
  'Exquisite',
  'Extraordinary',
  'Fantastic',
  'Fey',
  'Foul',
  'Galactic',
  'Ghastly',
  'Grand',
  'Grim',
  'Grotesque',
  'Hateful',
  'Hideous',
  'Horrible',
  'Incomparable',
  'Incomprehensible',
  'Inexplicable',
  'Infernal',
  'Ingenious',
  'Inscrutable',
  'Insidious',
  'Iridescent',
  'Jocular',
  'Lawful',
  'Legendary',
  'Loathsome',
  'Magnificent',
  'Majestic',
  'Marvelous',
  'Masterful',
  'Miraculous',
  'Mysterious',
  'Noetic',
  'Noxious',
  'Odious',
  'Ominous',
  'Original',
  'Orthodox',
  'Ostentatious',
  'Otherworldly',
  'Peculiar',
  'Pernicious',
  'Phenomenal',
  'Place trait',
  'Planar',
  'Planetary',
  'Preeminent',
  'Primal',
  'Primeval',
  'Primordial',
  'Prodigious',
  'Psychedelic',
  'Remarkable',
  'Resplendent',
  'Royal',
  'Sacred',
  'Scent',
  'Sinister',
  'Sound',
  'Splendid',
  'Subtle',
  'Superior',
  'Supreme',
  'Taste',
  'Texture',
  'True',
  'Uncanny',
  'Unfathomable',
  'Unnatural',
  'Unorthodox',
  'Unspeakable',
  'Vile',
  'Whimsical',
  'Wondrous',
  'Wretched',
]

const elements = [
  'Acid',
  'Amber',
  'Ash',
  'Beer',
  'Bile',
  'Blood',
  'Blossom',
  'Bone',
  'Brass',
  'Brimstone',
  'Brine',
  'Butter',
  'Chalk',
  'Chaos',
  'Clay',
  'Cloud',
  'Cold',
  'Crystal',
  'Darkness',
  'Death',
  'Domain',
  'Dream',
  'Dust',
  'Fabric',
  'Flame',
  'Flesh',
  'Foam',
  'Fog',
  'Food',
  'Frost',
  'Fume',
  'Fungus',
  'Ghost',
  'Glass',
  'Glue',
  'Gravel',
  'Hail',
  'Heat',
  'Honey',
  'Ice',
  'Incense',
  'Ink',
  'Iron',
  'Ivory',
  'Lava',
  'Lead',
  'Leaf',
  'Light',
  'Lightning',
  'Marmalade',
  'Material',
  'Memory',
  'Miasma',
  'Moss',
  'Mud',
  'Nectar',
  'Oatmeal',
  'Obsidian',
  'Oil',
  'Paint',
  'Paper',
  'Perfume',
  'Plague',
  'Poison',
  'Pollen',
  'Quicksilver',
  'Radiation',
  'Rain',
  'Root',
  'Rot',
  'Salt',
  'Sand',
  'Sap',
  'Shadow',
  'Silk',
  'Slime',
  'Smoke',
  'Snow',
  'Soot',
  'Spark',
  'Speed',
  'Spore',
  'Steam',
  'Stench',
  'Stone',
  'Storm',
  'Sugar',
  'Syrup',
  'Taffy',
  'Tar',
  'Tea',
  'Tears',
  'Thorn',
  'Vine',
  'Void',
  'Water',
  'Wax',
  'Wind',
  'Wine',
  'Wood',
]

const forms = [
  'Animal',
  'Arc',
  'Archer',
  'Armor',
  'Arrow',
  'Aura',
  'Avalanche',
  'Axe',
  'Beacon',
  'Beam',
  'Beast',
  'Blade',
  'Blast',
  'Blob',
  'Bolt',
  'Bubble',
  'Cage',
  'Carriage',
  'Chain',
  'Chariot',
  'Circle',
  'Cloak',
  'Clothing',
  'Cloud',
  'Coil',
  'Colossus',
  'Column',
  'Cone',
  'Crown',
  'Cube',
  'Disk',
  'Dragon',
  'Eye',
  'Fang',
  'Finger',
  'Fissure',
  'Fist',
  'Flood',
  'Fly',
  'Fountain',
  'Gate',
  'Gaze',
  'Geyser',
  'Gloves',
  'Guardian',
  'Hammer',
  'Hand',
  'Hawk',
  'Horn',
  'Hound',
  'Key',
  'Knife',
  'Knight',
  'Mask',
  'Mechanism',
  'Misc. item',
  'Monolith',
  'Monster',
  'Mouth',
  'Organ',
  'Path',
  'Pit',
  'Pool',
  'Pulse',
  'Pyramid',
  'Ray',
  'Rune',
  'Sanctuary',
  'Serpent',
  'Servant',
  'Shield',
  'Skeleton',
  'Skin',
  'Song',
  'Spear',
  'Sphere',
  'Spider',
  'Spike',
  'Spray',
  'Staff',
  'Steed',
  'Storm',
  'Strike',
  'Structure',
  'Symbol',
  'Tangle',
  'Tool',
  'Torrent',
  'Touch',
  'Tree',
  'Tunnel',
  'Vortex',
  'Wall',
  'Wave',
  'Weapon',
  'Web',
  'Wheel',
  'Whip',
  'Word',
  'Zone',
]

const symbols = [
  'Animal',
  'Antlers',
  'Arrow',
  'Axe',
  'Bear',
  'Bell',
  'Bird',
  'Blood drop',
  'Book',
  'Boots',
  'Bow',
  'Bowl',
  'Branch',
  'Brazier',
  'Cauldron',
  'Chain',
  'Chariot',
  'Circle',
  'Clothing',
  'Cloud',
  'Coin',
  'Constellation',
  'Crab',
  'Cross',
  'Crown',
  'Crystal',
  'Dagger',
  'Deer',
  'Dice',
  'Eye',
  'Fangs',
  'Feather',
  'Fish',
  'Fist',
  'Flower',
  'Fountain',
  'Food',
  'Form',
  'Fox',
  'Frog',
  'Gate',
  'Goat',
  'Hammer',
  'Hand',
  'Heart',
  'Helmet',
  'Hook',
  'Horn',
  'Horse',
  'Hourglass',
  'Key',
  'Knot',
  'Lamp',
  'Leaf',
  'Lightning bolt',
  'Lock',
  'Mask',
  'Misc. item',
  'Moon',
  'Nut',
  'Octopus',
  'Organ',
  'Ox',
  'Pen',
  'Planet',
  'Rabbit',
  'Rat',
  'Ring',
  'Scorpion',
  'Scales',
  'Scroll',
  'Serpent',
  'Shield',
  'Sickle',
  'Skull',
  'Snail',
  'Snowflake',
  'Spear',
  'Spiral',
  'Square',
  'Staff',
  'Star',
  'Sun',
  'Sword',
  'Tentacle',
  'Throne',
  'Tooth',
  'Torch',
  'Tree',
  'Triangle',
  'Turtle',
  'Wave',
  'Weapon',
  'Web',
  'Whale',
  'Whip',
  'Wings',
  'Wolf',
]

const tools = [
  'Acid vial',
  'Animal scent',
  'Antitoxin',
  'Astrolabe',
  'Bandoleer',
  'Bear trap',
  'Bedroll',
  'Beeswax',
  'Bell',
  'Bellows',
  'Birdcage',
  'Blank book',
  'Blanket',
  'Block and tackle',
  'Boltcutters',
  'Bottle',
  'Bucket',
  'Bullseye lantern',
  'Caltrops',
  'Candle',
  'Censer',
  'Chain',
  'Chalk',
  'Chisel',
  'Climbing hook',
  'Compass',
  'Copper wire',
  'Crowbar',
  'Dice',
  'Door ram',
  'Ear trumpet',
  'Ether',
  'Fire oil',
  'Fishing hook',
  'Flashbomb',
  'Flashpowder',
  'Garlic',
  'Glue',
  'Grappling hook',
  'Grease',
  'Hacksaw',
  'Hammer',
  'Hand drill',
  'Hemp rope',
  'Hog holder',
  'Hooded lantern',
  'Hound',
  'Hourglass',
  'Incense',
  'Iron pot',
  'Iron tongs',
  'Lantern',
  'Large sack',
  'Lockpicks',
  'Lodestone',
  'Magnifying lens',
  'Manacles',
  'Marbles',
  'Metal File',
  'Mortar and pestle',
  'Mule',
  'Net',
  'Padlock and key',
  'Pen and ink',
  'Pickaxe',
  'Pitchfork',
  'Piton',
  'Pliers',
  'Poison',
  'Pole (10’)',
  'Pure alcohol',
  'Rat',
  'Rum',
  'Salve',
  'Scissors',
  'Sealing wax',
  'Sewing needle',
  'Sextant',
  'Shovel',
  'Silk rope',
  'Sledgehammer',
  'Smokebomb',
  'Smoked goggles',
  'Soap',
  'Spikes',
  'Spyglass',
  'Stake',
  'Steel mirror',
  'Sundial',
  'Tent',
  'Thick gloves',
  'Tinderbox',
  'Torch',
  'Trumpet',
  'Twine',
  'Vial',
  'Waterskin',
  'Whetstone',
  'Whistle',
  'Wolfsbane',
]

const miscellaneousItems = [
  'Amulet',
  'Arrowhead',
  'Birdcage',
  'Book',
  'Bowl',
  'Box',
  'Brooch',
  'Button',
  'Card',
  'Cipher',
  'Clock',
  'Clothing',
  'Coin',
  'Comb',
  'Crystal',
  'Cup',
  'Degree',
  'Doll',
  'Drum',
  'Egg',
  'Embroidery',
  'Fabric',
  'Feather',
  'Figurine',
  'Finger bone',
  'Flag',
  'Flute',
  'Food',
  'Food recipe',
  'Fork',
  'Game piece',
  'Gem',
  'Hair oil',
  'Hairbrush',
  'Handkerchief',
  'Horn',
  'Icon',
  'Ingredient',
  'Jar',
  'Key',
  'Knife',
  'Ladle',
  'Leg bone',
  'Lens',
  'Letter',
  'List of demands',
  'Lock of hair',
  'Locket',
  'Lotion',
  'Lute',
  'Lyre',
  'Manifesto',
  'Map',
  'Mascara',
  'Material',
  'Military orders',
  'Mirror',
  'Orb',
  'Organ',
  'Paintbrush',
  'Painting',
  'Passport',
  'Pearl',
  'Perfume',
  'Pipe',
  'Pipes',
  'Poem',
  'Portrait',
  'Potion',
  'Potion recipe',
  'Prayer',
  'Pressed flower',
  'Purse',
  'Puzzle box',
  'Pyramid',
  'Razor',
  'Ribbon',
  'Ring',
  'Rouge',
  'Shopping list',
  'Signet ring',
  'Sketchbook',
  'Skull',
  'Snuffbox',
  'Spatula',
  'Spell scroll',
  'Spellbook',
  'Spoon',
  'Star chart',
  'Ticket',
  'Tool',
  'Tooth',
  'Treasure',
  'Treaty',
  'Tuning fork',
  'Wand',
  'Warrant',
  'Weapon',
  'Wine',
  'Yarn',
]

const weapons = [
  'Arming sword',
  'Backsword',
  'Bardiche',
  'Baton',
  'Battleaxe',
  'Beheading sword',
  'Bill hook',
  'Blowgun',
  'Blowpipe',
  'Boar spear',
  'Bolas',
  'Boomerang',
  'Brass knuckles',
  'Bullet crossbow',
  'Butterfly sword',
  'Censer flail',
  'Cestus',
  'Chain whip',
  'Chakram',
  'Claymore',
  'Club',
  'Crossbow',
  'Cutlass',
  'Dagger',
  'Dao',
  'Deer horn knives',
  'Dirk',
  'Double flail',
  'Emeici',
  'Falchion',
  'Flail',
  'Flambard',
  'Flying claws',
  'Gauntlet sword',
  'Gladius',
  'Glaive',
  'Halberd',
  'Hatchet',
  'Hook sword',
  'Horsebow',
  'Hunting knife',
  'Ice pick',
  'Javelin',
  'Katana',
  'Katar',
  'Khopesh',
  'Kukri',
  'Lance',
  'Lasso',
  'Longbow',
  'Longsword',
  'Lucerne hammer',
  'Mace',
  'Machete',
  'Man catcher',
  'Maul',
  'Messer',
  'Meteor hammer',
  'Military fork',
  'Morningstar',
  'Nunchaku',
  'Pickaxe',
  'Pike',
  'Poleaxe',
  'Push dagger',
  'Ranseur',
  'Rapier',
  'Recurve bow',
  'Rondel dagger',
  'Rope dart',
  'Sabre',
  'Sai',
  'Scimitar',
  'Scourge',
  'Shortbow',
  'Shortsword',
  'Shuriken',
  'Sickle',
  'Side sword',
  'Sling',
  'Slingshot',
  'Spear',
  'Staff',
  'Stave sling',
  'Stiletto',
  'Swordstaff',
  'Tanto',
  'Three-part staff',
  'Throwing axe',
  'Throwing knife',
  'Tiger claws',
  'Tonfa',
  'Trident',
  'Triple flail',
  'Wakizashi',
  'War scythe',
  'Warhammer',
  'Warpick',
  'Whip',
  'Zweihander',
]

const itemTraits = [
  'Ancient',
  'Avant-garde',
  'Blessed',
  'Bloody',
  'Brittle',
  'Broken',
  'Bulky',
  'Carved',
  'Classy',
  'Cold',
  'Collectible',
  'Color',
  'Compact',
  'Crusty',
  'Cultural value',
  'Cursed',
  'Cutting edge',
  'Damaged',
  'Damp',
  'Defective',
  'Detects foes',
  'Disguised',
  'Draws foes',
  'Dusty',
  'Edible',
  'Effect',
  'Element',
  'Embellished',
  'Encoded',
  'Eroded',
  'Expandable',
  'Extra-planar',
  'Famous',
  'Fashionable',
  'Filthy',
  'Flaking',
  'Floppy',
  'Foldable',
  'Forbidden',
  'Fragile',
  'Gaudy',
  'Glowing',
  'Gold-plated',
  'Gooey',
  'Gorgeous',
  'Heavy',
  'Hot',
  'Icy',
  'Immovable',
  'Impractical',
  'Indestructible',
  'Infamous',
  'Intelligent',
  'Kitchy',
  'Loud',
  'Lukewarm',
  'Luxurious',
  'Masterwork',
  'Military value',
  'Miniature',
  'Minimalist',
  'Modified',
  'Mythic',
  'Non-human',
  'Organic',
  'Oversized',
  'Owned',
  'Padded',
  'Painted',
  'Partial',
  'Perfumed',
  'Personality',
  'Political value',
  'Prickly',
  'Pulsing',
  'Reflective',
  'Refurbished',
  'Religious value',
  'Repaired',
  'Reviled',
  'Rotting',
  'Scent',
  'Sharp',
  'Shiny',
  'Shoddy',
  'Silent',
  'Slippery',
  'Smoke-stained',
  'Sound',
  'Spiky',
  'Squishy',
  'Sticky',
  'Stinky',
  'Talking',
  'Texture',
  'Toxic',
  'Twitching',
  'Ugly',
  'Vulgar',
  'Whispering',
]

const maleNames = [
  'Alaric',
  'Aldous',
  'Alton',
  'Archibald',
  'Arne',
  'Arthur',
  'Balthazar',
  'Bard',
  'Bartholomew',
  'Bartlett',
  'Basil',
  'Baxton',
  'Benedict',
  'Bennett',
  'Beorn',
  'Bertram',
  'Burchard',
  'Cadman',
  'Caspian',
  'Chadwick',
  'Clovis',
  'Conrad',
  'Corbett',
  'Crispin',
  'Cyprian',
  'Cyrus',
  'Daegal',
  'Denis',
  'Destrian',
  'Drogo',
  'Eldon',
  'Ellis',
  'Elric',
  'Emil',
  'Erasmus',
  'Faustus',
  'Felix',
  'Finn',
  'Finnian',
  'Fitzhugh',
  'Florian',
  'Fox',
  'Galileo',
  'Giles',
  'Godfrey',
  'Godwin',
  'Grimwald',
  'Hamlin',
  'Hannibal',
  'Hildebrand',
  'Jasper',
  'Jeremiah',
  'Johan',
  'Jules',
  'Kenric',
  'Leif',
  'Leopold',
  'Leoric',
  'Lothar',
  'Lucian',
  'Merrick',
  'Milo',
  'Mordred',
  'Mortimer',
  'Neville',
  'Odel',
  'Ogden',
  'Orion',
  'Orvyn',
  'Osric',
  'Oswald',
  'Paschal',
  'Percival',
  'Peregrine',
  'Piers',
  'Quentin',
  'Randolf',
  'Redmaine',
  'Reinhold',
  'Rex',
  'Ricard',
  'Roland',
  'Rufus',
  'Silas',
  'Stilton',
  'Stratford',
  'Sylvio',
  'Tenpiece',
  'Thaddeus',
  'Torsten',
  'Tristan',
  'Urban',
  'Valentin',
  'Valerian',
  'Virgil',
  'Warrick',
  'Waverly',
  'Webster',
  'Wilkin',
  'Wymond',
]

const femaleNames = [
  'Adelaide',
  'Agnes',
  'Alma',
  'Anastasia',
  'Anika',
  'Annora',
  'Astrid',
  'Barsaba',
  'Beatrix',
  'Bethel',
  'Bianca',
  'Blanche',
  'Bodil',
  'Bridget',
  'Brunhilde',
  'Calypso',
  'Catalina',
  'Cecilia',
  'Celeste',
  'Charlotte',
  'Cleopha',
  'Clotilde',
  'Clover',
  'Colette',
  'Constance',
  'Damaris',
  'Daphne',
  'Demona',
  'Desirae',
  'Ella',
  'Elsbeth',
  'Esme',
  'Eulalia',
  'Euphemia',
  'Eydis',
  'Fern',
  'Fiora',
  'Fleur',
  'Florence',
  'Francesca',
  'Gertrude',
  'Giselle',
  'Godiva',
  'Guinevere',
  'Heloise',
  'Henrietta',
  'Hester',
  'Hippolyta',
  'Honora',
  'Ingrid',
  'Ione',
  'Iris',
  'Isabetta',
  'Isolde',
  'Jacquette',
  'Jeanne',
  'Jessamine',
  'Jilly',
  'Lavinia',
  'Lisbet',
  'Madelena',
  'Margot',
  'Marian',
  'Marigold',
  'Matilda',
  'Melisande',
  'Millicent',
  'Minerva',
  'Morgan',
  'Nerissa',
  'Odette',
  'Olga',
  'Olivia',
  'Orchid',
  'Pepper',
  'Petra',
  'Philomena',
  'Phoebe',
  'Piety',
  'Poppy',
  'Portia',
  'Rosalind',
  'Rose',
  'Sabina',
  'Sif',
  'Sigourney',
  'Sigrid',
  'Silence',
  'Sybil',
  'Tabitha',
  'Trillby',
  'Ulfhild',
  'Ursula',
  'Vivian',
  'Wendy',
  'Willow',
  'Winifred',
  'Yvette',
]

const surname1 = [
  'Adder-',
  'Apple-',
  'Ash-',
  'Bab-',
  'Bag-',
  'Bar-',
  'Barrow-',
  'Basker-',
  'Beau-',
  'Beetle-',
  'Berry-',
  'Bird-',
  'Brandy-',
  'Bright-',
  'Brindle-',
  'Bull-',
  'Bux-',
  'Caven-',
  'Chelten-',
  'Chester-',
  'Chuff-',
  'Chum-',
  'Clod-',
  'Cobble-',
  'Cotten-',
  'Cress-',
  'Crom-',
  'Cumber-',
  'Dela-',
  'Dig-',
  'Draw-',
  'Dreg-',
  'Drol-',
  'Dun-',
  'Even-',
  'Ever-',
  'Fair-',
  'Fallow-',
  'Farthing-',
  'Feather-',
  'Ferns-',
  'Fox-',
  'Gam-',
  'Gird-',
  'Gos-',
  'Grey-',
  'Grim-',
  'Half-',
  'Hard-',
  'Harrow-',
  'Hart-',
  'Haver-',
  'Hedge-',
  'Hither-',
  'Holly-',
  'Honey-',
  'Horn-',
  'Kettle-',
  'Kings-',
  'Little-',
  'Long-',
  'Love-',
  'Middle-',
  'Mug-',
  'Nether-',
  'Never-',
  'Obling-',
  'Pember-',
  'Penning-',
  'Pinker-',
  'Porten-',
  'Quill-',
  'Rath-',
  'Sack-',
  'Sallow-',
  'Salt-',
  'Scor-',
  'Sedge-',
  'Silver-',
  'Slither-',
  'Smit-',
  'Snod-',
  'Souther-',
  'Stew-',
  'Stir-',
  'Swine-',
  'Tar-',
  'Temple-',
  'Tide-',
  'Tread-',
  'Under-',
  'Vander-',
  'Weather-',
  'Wester-',
  'Wex-',
  'Whit-',
  'Wither-',
  'Withing-',
  'Wy-',
]

const surname2 = [
  '-bald',
  '-barrow',
  '-batch',
  '-beck',
  '-blood',
  '-bold',
  '-bone',
  '-bottle',
  '-bottom',
  '-bridge',
  '-buck',
  '-burn',
  '-bury',
  '-by',
  '-caster',
  '-castle',
  '-chester',
  '-child',
  '-church',
  '-cliff',
  '-cloth',
  '-coat',
  '-combe',
  '-cott',
  '-dale',
  '-dish',
  '-ditch',
  '-down',
  '-fax',
  '-feld',
  '-fent',
  '-fer',
  '-field',
  '-foot',
  '-force',
  '-fort',
  '-fry',
  '-gale',
  '-grass',
  '-grave',
  '-green',
  '-grove',
  '-ham',
  '-hill',
  '-hope',
  '-lack',
  '-lain',
  '-land',
  '-less',
  '-lin',
  '-ling',
  '-lish',
  '-lock',
  '-long',
  '-low',
  '-ly',
  '-man',
  '-march',
  '-mark',
  '-marl',
  '-marsh',
  '-mass',
  '-meer',
  '-mond',
  '-mont',
  '-mor',
  '-morn',
  '-nick',
  '-ny',
  '-port',
  '-ridge',
  '-row',
  '-sea',
  '-set',
  '-shot',
  '-sop',
  '-spoon',
  '-staff',
  '-stoke',
  '-stone',
  '-ten',
  '-thorn',
  '-thorpe',
  '-throp',
  '-ton',
  '-tooth',
  '-top',
  '-vane',
  '-ville',
  '-wald',
  '-wark',
  '-watch',
  '-water',
  '-well',
  '-whistle',
  '-wick',
  '-wood',
  '-worm',
  '-worth',
  '-worthy',
]

export function randomSurname() {
  return `${randomElement(surname1)}${randomElement(surname2)}`.replace(/^--/, '')
}

const npcDetails = [
  'Acid scar',
  'Aquiline face',
  'Arrow scar',
  'Athletic',
  'Bad eyesight',
  'Bald',
  'Balding',
  'Beautiful',
  'Birthmark',
  'Bite mark',
  'Blade scar',
  'Blind',
  'Blunt face',
  'Bony',
  'Braided hair',
  'Brawny',
  'Bristly hair',
  'Broken nose',
  'Burn scar',
  'Bushy brows',
  'Childish face',
  'Chiseled face',
  'Claw scar',
  'Coiffed',
  'Corpulent',
  'Craggy face',
  'Crooked teeth',
  'Cropped hair',
  'Curly hair',
  'Deaf',
  'Delicate face',
  'Dreadlocks',
  'Filthy hair',
  'Flabby',
  'Flat face',
  'Frail',
  'Freckles',
  'Furrowed face',
  'Gaunt',
  'Gold tooth',
  'Hard of hearing',
  'Hulking',
  'Lanky',
  'Lantern jaw',
  'Limp',
  'Lumpy face',
  'Luxurious hair',
  'Missing arm',
  'Missing ear',
  'Missing eye',
  'Missing finger',
  'Missing foot',
  'Missing hand',
  'Missing leg',
  'Missing teeth',
  'Mutation',
  'Mute',
  'No eyebrows',
  'Noose scar',
  'Oily',
  'Pageboy hair',
  'Perfect posture',
  'Perfumed',
  'Piercings',
  'Pointed face',
  'Ponytail',
  'Pox scars',
  'Ripped',
  'Ritual scar',
  'Rosy face',
  'Rotten teeth',
  'Round face',
  'Rugged',
  'Scrawny',
  'Shaggy hair',
  'Sharp teeth',
  'Shriveled',
  'Silky hair',
  'Sinewy',
  'Slender',
  'Slicked hair',
  'Slouched',
  'Smelly',
  'Square face',
  'Squint',
  'Statuesque',
  'Stout',
  'Sweaty',
  'Tattooed',
  'Tiny',
  'Topknot',
  'Towering',
  'Twisted lip',
  'Very long hair',
  'Warts',
  'Wavy hair',
  'Weathered face',
  'Willowy',
  'Wiry',
  'Wispy hair',
]

const animals = [
  'Ant',
  'Anteater',
  'Ape',
  'Badger',
  'Bat',
  'Bear',
  'Beaver',
  'Bee',
  'Beetle',
  'Boar',
  'Bulldog',
  'Butterfly',
  'Camel',
  'Cat',
  'Centipede',
  'Chameleon',
  'Cobra',
  'Cockroach',
  'Constrictor',
  'Cougar',
  'Cow',
  'Coyote',
  'Crab',
  'Crane',
  'Cricket',
  'Crocodile',
  'Crow',
  'Cuckoo',
  'Donkey',
  'Dragonfly',
  'Duck',
  'Eagle',
  'Eel',
  'Elephant',
  'Elk',
  'Falcon',
  'Firefly',
  'Fox',
  'Frog',
  'Goat',
  'Goose',
  'Hare',
  'Hart',
  'Hawk',
  'Hedgehog',
  'Hornet',
  'Horse',
  'Hound',
  'Hummingbird',
  'Jackal',
  'Jellyfish',
  'Leech',
  'Lion',
  'Locust',
  'Lynx',
  'Mantis',
  'Mastodon',
  'Mockingbird',
  'Mole',
  'Monkey',
  'Moose',
  'Moth',
  'Mouse',
  'Mule',
  'Octopus',
  'Otter',
  'Owl',
  'Ox',
  'Panther',
  'Pig',
  'Pony',
  'Porcupine',
  'Possum',
  'Rabbit',
  'Raccoon',
  'Rat',
  'Reindeer',
  'Rooster',
  'Salamander',
  'Scorpion',
  'Seal',
  'Shark',
  'Sheep',
  'Slug',
  'Snail',
  'Sparrow',
  'Spider',
  'Squid',
  'Squirrel',
  'Tiger',
  'Toad',
  'Turtle',
  'Viper',
  'Vulture',
  'Walrus',
  'Weasel',
  'Whale',
  'Wolf',
  'Wolverine',
  'Worm',
]

const monsterTraits = [
  'Acid blood',
  'Amphibious',
  'Ancient',
  'Animated',
  'Asymmetrical',
  'Bloated',
  'Bloodless',
  'Brittle',
  'Burning',
  'Charged',
  'Clay-like',
  'Colossal',
  'Crystalline',
  'Decaying',
  'Delusion',
  'Elongated',
  'Ethereal',
  'Ever-young',
  'Eyeless',
  'Faceless',
  'Flaking',
  'Flammable',
  'Flexible',
  'Fluffy',
  'Foaming',
  'Fungal',
  'Fuzzy',
  'Gaseous',
  'Gelatinous',
  'Geometric',
  'Hair shedding',
  'Hairless',
  'Hairy',
  'Hardened',
  'Headless',
  'Ice-cold',
  'Illusory',
  'Iridescent',
  'Large head',
  'Legless',
  'Liquid',
  'Luminous',
  'Lumpy',
  'Many arms',
  'Many eyes',
  'Many faces',
  'Many heads',
  'Many legs',
  'Many mouths',
  'Mechanical',
  'Metallic',
  'Mismatched limbs',
  'Molting',
  'Muscular',
  'Mutation',
  'No neck',
  'One eye',
  'Ooze-form',
  'Personality',
  'Poisonous',
  'Powdery',
  'Pulsing',
  'Radioactive',
  'Reflective',
  'Rubbery',
  'Scent',
  'Shadowy',
  'Sharp',
  'Short limbs',
  'Shriveled',
  'Skeletal',
  'Skin shedding',
  'Slimy',
  'Smoking',
  'Soft',
  'Sooty',
  'Sparking',
  'Steaming',
  'Sticky',
  'Stinking',
  'Stone-like',
  'Stretchy',
  'Tactic',
  'Texture',
  'Tiny',
  'Translucent',
  'Tree-like',
  'Two-dimensional',
  'Venomous',
  'Vibrating',
  'Waxy',
  'Weakness',
]

const powers = [
  'Absorb abilities',
  'Acid aura',
  'Acid bolt',
  'Acid breath',
  'Astral projection',
  'Attract',
  'Beast control',
  'Bird control',
  'Blind',
  'Blur',
  'Burrow',
  'Chameleon skin',
  'Clairaudience',
  'Clairvoyance',
  'Clone self',
  'Create illusion',
  'Deafen',
  'Drain life',
  'Dreamwalk',
  'Earthquake',
  'Echolocation',
  'Electric aura',
  'Element aura',
  'Element blast',
  'Element bolt',
  'Element breath',
  'Element control',
  'Element ray',
  'Element wall',
  'Entangle',
  'Entomb',
  'Explode',
  'Fear aura',
  'Fire aura',
  'Fire bolt',
  'Fire breath',
  'Fire control',
  'Fire starting',
  'Fire wall',
  'Fog breath',
  'Force wall',
  'Friendship aura',
  'Gravity control',
  'Grow plants',
  'Hate aura',
  'Healing aura',
  'Hypnotism',
  'Ice aura',
  'Ice bolt',
  'Ice breath',
  'Ice wall',
  'Immovability',
  'Insect control',
  'Iron wall',
  'Laser eyes',
  'Levitation',
  'Lightning bolt',
  'Lightning breath',
  'Love aura',
  'Magnetism',
  'Memory control',
  'Mimic sounds',
  'Mind control',
  'Mold flesh',
  'Mold metal',
  'Mold stone',
  'Paralyze',
  'Paranoia aura',
  'Petrify',
  'Plane shift',
  'Plant control',
  'Poison aura',
  'Poison breath',
  'Rage aura',
  'Raise dead',
  'Remove curse',
  'Repulse',
  'Rot',
  'Shockwave',
  'Silence',
  'Sleep aura',
  'Slow enemies',
  'Spell',
  'Spirit control',
  'Stone wall',
  'Summon',
  'Swallow whole',
  'Swap minds',
  'Teleport',
  'Time control',
  'Travel shift',
  'Undead control',
  'Wind control',
  'Wind wall',
]

const tactics = [
  'Ambush',
  'Annoy',
  'Bind',
  'Blind',
  'Body slam',
  'Break armor',
  'Break terrain',
  'Break weapons',
  'Bulldoze',
  'Burrow',
  'Burst',
  'Cannibalize',
  'Capture',
  'Challenge',
  'Chant',
  'Charge',
  'Cheat',
  'Choke',
  'Climb',
  'Confuse',
  'Create barrier',
  'Cripple',
  'Deafen',
  'Deceive',
  'Demand worship',
  'Disarm',
  'Disorient',
  'Distract',
  'Divide foes',
  'Dodge',
  'Drop down',
  'Effect',
  'Encircle',
  'Entangle',
  'Evade',
  'Feint',
  'Flank',
  'Follow',
  'Frighten',
  'Gang up',
  'Go berserk',
  'Goad',
  'Grab',
  'Harry',
  'Ignite',
  'Immobilize',
  'Leap',
  'Link up',
  'Lure in',
  'Manipulate',
  'Merge',
  'Mire',
  'Monologue',
  'Negotiate',
  'Obscure',
  'Order minion',
  'Pincer maneuver',
  'Play dead',
  'Poison',
  'Power up',
  'Praise self',
  'Protect leader',
  'Protect self',
  'Pull',
  'Push',
  'Roll',
  'Scatter foes',
  'Scream',
  'Shake',
  'Sicken',
  'Slam object',
  'Spin',
  'Split body',
  'Squeeze',
  'Stalk',
  'Stare down',
  'Steal',
  'Strategic retreat',
  'Stun',
  'Summon aid',
  'Swallow whole',
  'Swarm',
  'Sweep',
  'Swing creature',
  'Swing object',
  'Target insolent',
  'Target leader',
  'Target nearest',
  'Target richest',
  'Target strongest',
  'Target weakest',
  'Throw creature',
  'Throw object',
  'Thrust',
  'Toy with',
  'Trap',
  'Trap effect',
  'Trip',
  'Vomit',
]

export const allArrays = {
  animals,
  background,
  backgroundDescription,
  careers,
  clothing,
  dungeoneeringGear,
  elements,
  femaleNames,
  forms,
  generalGear1,
  generalGear2,
  hair,
  helmetsAndShields,
  itemTraits,
  maleNames,
  miscellaneousItems,
  misfortunes,
  monsterTraits,
  npcDetails,
  powers,
  qualities,
  skin,
  speech,
  surname1,
  surname2,
  symbols,
  tactics,
  tools,
  travelShifts,
  vice,
  virtue,
  weapons,
}
